function betaA = DefBeta(Jab, Ea, mExtZero, mExtOne, qA0, theta, ...
                         delta, cff) 
  betaA = Jab.^2 * qA0 + (Ea.^2 / cff) * (mExtZero.^2 + (1/2.0) ...
                                               * mExtOne.^2 * cos(4 ...
                                                       * delta));
end
